import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/shared/Footer";
import Header from "./components/shared/Header";
import { QueryClientProviderWrapper } from "@/queryClientProvider";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/authProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-gray-300 `}
      >
        <QueryClientProviderWrapper>
          <AuthProvider>
     
          <Header />
        <main className="w-full max-w-6xl mx-auto min-h-screen flex flex-col justify-start items-center">{children}</main>
        <Footer />
           <Toaster toastOptions={{
            style:{
              fontFamily:"monospace",
              fontWeight:"bold",
              fontSize:"14px",
              padding:"10px",
              borderRadius:"5px"
            },
            success:{
              style:{
                backgroundColor:"green",
                color:"white"
              }
            },
            error:{
              style:{
                backgroundColor:"red",
                color:"white"
              }
            }
           }}/>
  </AuthProvider>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
